// AUTO-GENERATED by scripts/generate-package-registry.ts — do not edit.
// Regenerate with: npm run packages:generate
import { overlayPackageConfigSchema, type OverlayPackageConfig } from './types'
import Config0 from '@/projects/default/project.config'

export const generatedPackages: OverlayPackageConfig[] = [
  overlayPackageConfigSchema.parse(Config0),
]
