// Package discovery is build-time codegen, not a runtime dynamic import: a fully
// dynamic import() (even with webpackIgnore/turbopackIgnore) is invisible to
// Next.js's build-time output file tracing, so projects/**/project.config.ts
// would silently be missing from the deployed Netlify function. Emitting plain
// static imports works everywhere — same fix already applied to titles.
import { PROJECTS_DIR, listOverlayPackageLabels } from './packages'

export function scanPackageLabels(root: string = PROJECTS_DIR): string[] {
  return listOverlayPackageLabels(root)
}

export function buildPackageRegistrySource(labels: string[]) {
  const imports = labels
    .map((label, i) => `import Config${i} from '@/projects/${label}/project.config'`)
    .join('\n')

  const entries = labels
    .map((label, i) => `  overlayPackageConfigSchema.parse(Config${i}),`)
    .join('\n')

  return `// AUTO-GENERATED by scripts/generate-package-registry.ts — do not edit.
// Regenerate with: npm run packages:generate
import { overlayPackageConfigSchema, type OverlayPackageConfig } from './types'
${imports}

export const generatedPackages: OverlayPackageConfig[] = [
${entries}
]
`
}
