// Title discovery is build-time codegen, not a runtime glob: import.meta.glob is
// Vite-only and require.context is webpack-only, but this app must resolve titles
// under BOTH Turbopack and Vitest. Emitting plain static imports works everywhere.
import { existsSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { PROJECTS_DIR } from '@/lib/projects/packages'

export type TitleLocation = {
  packageLabel: string
  key: string
}

const REQUIRED_FILES = ['index.tsx', 'model.ts', 'settings.ts']

export function scanTitleDirs(root: string = PROJECTS_DIR): TitleLocation[] {
  if (!existsSync(root)) return []

  return readdirSync(root, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .flatMap((pkg) => {
      const titlesDir = join(root, pkg.name, 'titles')
      if (!existsSync(titlesDir)) return []
      return readdirSync(titlesDir, { withFileTypes: true })
        .filter((t) => t.isDirectory())
        .filter((t) => REQUIRED_FILES.every((f) => existsSync(join(titlesDir, t.name, f))))
        .map((t) => ({ packageLabel: pkg.name, key: t.name }))
    })
    .sort((a, b) => `${a.packageLabel}/${a.key}`.localeCompare(`${b.packageLabel}/${b.key}`))
}

export function buildRegistrySource(locations: TitleLocation[]) {
  const imports = locations
    .map((loc, i) => {
      const path = `@/projects/${loc.packageLabel}/titles/${loc.key}`
      return [
        `import Component${i} from '${path}'`,
        `import * as model${i} from '${path}/model'`,
        `import settings${i} from '${path}/settings'`,
      ].join('\n')
    })
    .join('\n')

  const entries = locations
    .map(
      (loc, i) => `  {
    key: '${loc.key}',
    packageLabel: '${loc.packageLabel}',
    Component: Component${i} as TitleEntry['Component'],
    model: model${i}.model,
    actions: model${i}.actions,
    settings: titleSettingsSchema.parse(settings${i}),
  },`,
    )
    .join('\n')

  return `// AUTO-GENERATED by scripts/generate-title-registry.ts — do not edit.
// Regenerate with: npm run titles:generate
import { titleSettingsSchema, type TitleEntry } from './types'
${imports}

export const generatedTitles: TitleEntry[] = [
${entries}
]
`
}
