// AUTO-GENERATED by scripts/generate-title-registry.ts — do not edit.
// Regenerate with: npm run titles:generate
import { titleSettingsSchema, type TitleEntry } from './types'
import Component0 from '@/projects/default/titles/lower-third'
import * as model0 from '@/projects/default/titles/lower-third/model'
import settings0 from '@/projects/default/titles/lower-third/settings'
import Component1 from '@/projects/default/titles/opening-timer'
import * as model1 from '@/projects/default/titles/opening-timer/model'
import settings1 from '@/projects/default/titles/opening-timer/settings'

export const generatedTitles: TitleEntry[] = [
  {
    key: 'lower-third',
    packageLabel: 'default',
    Component: Component0 as TitleEntry['Component'],
    model: model0.model,
    actions: model0.actions,
    settings: titleSettingsSchema.parse(settings0),
  },
  {
    key: 'opening-timer',
    packageLabel: 'default',
    Component: Component1 as TitleEntry['Component'],
    model: model1.model,
    actions: model1.actions,
    settings: titleSettingsSchema.parse(settings1),
  },
]
