// AUTO-GENERATED by scripts/generate-overlay-registry.ts — do not edit.
// Run: npm run titles:generate
import GeneralIntroSettings from '@/overlays/general/Intro/settings'
import * as GeneralIntroModel from '@/overlays/general/Intro/model'
import GeneralOpeningTimerSettings from '@/overlays/general/OpeningTimer/settings'
import * as GeneralOpeningTimerModel from '@/overlays/general/OpeningTimer/model'
import GeneralScoreboardSettings from '@/overlays/general/Scoreboard/settings'
import * as GeneralScoreboardModel from '@/overlays/general/Scoreboard/model'
import GeneralTextSettings from '@/overlays/general/Text/settings'
import * as GeneralTextModel from '@/overlays/general/Text/model'

export const catalog = [
  { category: 'general', template: 'Intro', settings: GeneralIntroSettings, zodModel: GeneralIntroModel.model, fields: GeneralIntroModel.fields, actions: GeneralIntroModel.actions },
  { category: 'general', template: 'OpeningTimer', settings: GeneralOpeningTimerSettings, zodModel: GeneralOpeningTimerModel.model, fields: GeneralOpeningTimerModel.fields, actions: GeneralOpeningTimerModel.actions },
  { category: 'general', template: 'Scoreboard', settings: GeneralScoreboardSettings, zodModel: GeneralScoreboardModel.model, fields: GeneralScoreboardModel.fields, actions: GeneralScoreboardModel.actions },
  { category: 'general', template: 'Text', settings: GeneralTextSettings, zodModel: GeneralTextModel.model, fields: GeneralTextModel.fields, actions: GeneralTextModel.actions },
] as const
