// AUTO-GENERATED by scripts/generate-overlay-registry.ts — do not edit.
// Run: npm run titles:generate
import GeneralTextSettings from '@/overlays/general/Text/settings'
import * as GeneralTextModel from '@/overlays/general/Text/model'

export const catalog = [
  { category: 'general', template: 'Text', settings: GeneralTextSettings, zodModel: GeneralTextModel.model, fields: GeneralTextModel.fields, actions: GeneralTextModel.actions },
] as const
