import { readdirSync, statSync, existsSync } from 'node:fs'
import { join } from 'node:path'

// Pure codegen logic (no file writes) so tests can import buildSources without
// side effects. scripts/generate-overlay-registry.ts is the thin runner.

export type OverlayDir = { category: string; template: string }

export function scanOverlayDirs(root = 'overlays'): OverlayDir[] {
  const dirs: OverlayDir[] = []
  if (!existsSync(root)) return dirs
  for (const category of readdirSync(root).sort()) {
    const catPath = join(root, category)
    if (!statSync(catPath).isDirectory()) continue
    for (const template of readdirSync(catPath).sort()) {
      const tplPath = join(catPath, template)
      if (!statSync(tplPath).isDirectory()) continue
      if (existsSync(join(tplPath, 'settings.ts'))) dirs.push({ category, template })
    }
  }
  return dirs
}

function pascal(s: string): string {
  return s.replace(/(^|[^a-zA-Z0-9])([a-zA-Z0-9])/g, (_m, _sep, c: string) => c.toUpperCase())
}

const HEADER = '// AUTO-GENERATED by scripts/generate-overlay-registry.ts — do not edit.\n'
  + '// Run: npm run titles:generate\n'

export function buildSources(dirs: OverlayDir[]): { catalog: string; components: string } {
  const sorted = [...dirs].sort((a, b) => (
    `${a.category}/${a.template}`.localeCompare(`${b.category}/${b.template}`)
  ))

  const catImports: string[] = []
  const catEntries: string[] = []
  const compImports: string[] = []
  const compEntries: string[] = []

  for (const { category, template } of sorted) {
    const id = pascal(category) + pascal(template)
    const path = `@/overlays/${category}/${template}`
    catImports.push(`import ${id}Settings from '${path}/settings'`)
    catImports.push(`import * as ${id}Model from '${path}/model'`)
    catEntries.push(
      `  { category: '${category}', template: '${template}', settings: ${id}Settings, `
      + `zodModel: ${id}Model.model, fields: ${id}Model.fields, actions: ${id}Model.actions },`,
    )

    compImports.push(`import ${id}Component from '${path}'`)
    compImports.push(`import ${id}AnimationIn from '${path}/animationIn'`)
    compImports.push(`import ${id}AnimationOut from '${path}/animationOut'`)
    compEntries.push(
      `  { category: '${category}', template: '${template}', Component: ${id}Component, `
      + `animationIn: ${id}AnimationIn, animationOut: ${id}AnimationOut },`,
    )
  }

  const catalog = `${HEADER}${catImports.join('\n')}\n\nexport const catalog = [\n${catEntries.join('\n')}\n] as const\n`
  const components = `${HEADER}${compImports.join('\n')}\n\nexport const components = [\n${compEntries.join('\n')}\n] as const\n`
  return { catalog, components }
}
