// AUTO-GENERATED by scripts/generate-overlay-registry.ts — do not edit.
// Run: npm run titles:generate
import GeneralIntroComponent from '@/overlays/general/Intro'
import GeneralIntroAnimationIn from '@/overlays/general/Intro/animationIn'
import GeneralIntroAnimationOut from '@/overlays/general/Intro/animationOut'
import GeneralOpeningTimerComponent from '@/overlays/general/OpeningTimer'
import GeneralOpeningTimerAnimationIn from '@/overlays/general/OpeningTimer/animationIn'
import GeneralOpeningTimerAnimationOut from '@/overlays/general/OpeningTimer/animationOut'
import GeneralScoreboardComponent from '@/overlays/general/Scoreboard'
import GeneralScoreboardAnimationIn from '@/overlays/general/Scoreboard/animationIn'
import GeneralScoreboardAnimationOut from '@/overlays/general/Scoreboard/animationOut'
import GeneralTextComponent from '@/overlays/general/Text'
import GeneralTextAnimationIn from '@/overlays/general/Text/animationIn'
import GeneralTextAnimationOut from '@/overlays/general/Text/animationOut'

export const components = [
  { category: 'general', template: 'Intro', Component: GeneralIntroComponent, animationIn: GeneralIntroAnimationIn, animationOut: GeneralIntroAnimationOut },
  { category: 'general', template: 'OpeningTimer', Component: GeneralOpeningTimerComponent, animationIn: GeneralOpeningTimerAnimationIn, animationOut: GeneralOpeningTimerAnimationOut },
  { category: 'general', template: 'Scoreboard', Component: GeneralScoreboardComponent, animationIn: GeneralScoreboardAnimationIn, animationOut: GeneralScoreboardAnimationOut },
  { category: 'general', template: 'Text', Component: GeneralTextComponent, animationIn: GeneralTextAnimationIn, animationOut: GeneralTextAnimationOut },
] as const
