// AUTO-GENERATED by scripts/generate-overlay-registry.ts — do not edit.
// Run: npm run titles:generate
import GeneralTextComponent from '@/overlays/general/Text'
import GeneralTextAnimationIn from '@/overlays/general/Text/animationIn'
import GeneralTextAnimationOut from '@/overlays/general/Text/animationOut'

export const components = [
  { category: 'general', template: 'Text', Component: GeneralTextComponent, animationIn: GeneralTextAnimationIn, animationOut: GeneralTextAnimationOut },
] as const
